### ISSUE TITLE
How about add DynMoE to the list?

### ISSUE THREAD

**Issue by QAQdev** [koayon/awesome-adaptive-computation#1]
Paper link: https://arxiv.org/abs/2405.14297
Code link: https://github.com/LINs-lab/DynMoE

**Comment by koayon** [comment]
Hi @QAQdev, thanks for sharing this paper - I think this would be a great one to add to the list! It's super interesting work!

Do you have a short description of your paper or key points that you think would be important here to include in the description? 

My initial understanding is that the approach allows us to determine the hyperparameters for experts activated and number of experts automatically and so reduces the time and compute needed for h-param sweeps. It also has the benefit of slightly increasing performance on downstream tasks (is this FLOP-matched? Seems like maybe not?). The areas for future work at this stage look to be optimising for the hardware (currently GPU memory is taken up by rarely used experts and there seems to be work on load balancing to increase throughput). Does this feel accurate?

Again, thanks so much for being part of and sharing this work - I really enjoyed reading it and it seems likely to become a new default for the MoE paradigm. Also great job releasing DeepSpeed-MoE flavoured code!

**Comment by QAQdev** [comment]
> Hi @QAQdev, thanks for sharing this paper - I think this would be a great one to add to the list! It's super interesting work!
> 
> Do you have a short description of your paper or key points that you think would be important here to include in the description?
> 
> My initial understanding is that the approach allows us to determine the hyperparameters for experts activated and number of experts automatically and so reduces the time and compute needed for h-param sweeps. It also has the benefit of slightly increasing performance on downstream tasks (is this FLOP-matched? Seems like maybe not?). The areas for future work at this stage look to be optimising for the hardware (currently GPU memory is taken up by rarely used experts and there seems to be work on load balancing to increase throughput). Does this feel accurate?
> 
> Again, thanks so much for being part of and sharing this work - I really enjoyed reading it and it seems likely to become a new default for the MoE paradigm. Also great job releasing DeepSpeed-MoE flavoured code!

Sorry for a late reply. I think your understanding is precise actually! As for the description, I think you can use your own language since you have capture the key points :)
